spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/Demo
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true



blockchain.rpc.url=https://sepolia.infura.io/v3/416cf7e439d94e4c9dcfae8d0ecb50b6
blockchain.private.key=e213ed744ac3d5525187ea636670e44b6822fd0538c25f65ddc2452f696f8f89
blockchain.contract.address=0x8451E36b345c0cE8c6824857eb6D29CC3A1d91cC
platform.wallet.address=0x415fd183C4E50f099eB11e52ee3ab17476915e63



pinata.api.key=b21c1e8998867b2a5167
pinata.secret.api.key=120ddcf1fe7b96599f04c35862636557d66b6a178b591e6bacc2325a610f2513


cloudinary.cloud-name=dnpxg7p4t
cloudinary.api-key=182147869246755
cloudinary.api-secret=OX9JanveLQLDtNF1QQv5RiCYSPQ

gemini.api.key=AIzaSyAeAJKMQH1Z_V1FRaSeqB0fN2kTdLHrZJ4


jwt.secret=/gNlUmka9TadHXPiwUniFysANsxlqKY6RmO2H4AFZA8=
jwt.expiration=86400000 